blog/urls.py
from django.urls import path, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
   
    path('', views.post_list, name='post_list'),
    path('category/<str:slug>/', views.category, name='category'),
    path('tags/<str:slug>/', views.tag, name='tag'),
    path('postcomment/', views.postcomment, name='postcomment'),
    path('post/<str:slug>/', views.post_detail, name='post_detail'),
    path('post-new/', views.post_new, name='post-new'),
    path('post/<str:slug>/edit/', views.post_edit, name='post_edit'),
    path('user/<int:user_id>/', views.user_detail, name='user_detail'),
    path('user_edit/<int:user_id>/',views. edit_profile,name='edit-profile'),
    path('login/', views.user_login, name='user-login'),
    path('signup/', views.user_signup, name='user-signup'),
    path('signout/', views.user_signout, name='user-signout'),
    # path('profile/', views.edit_profile, name='edit-profile'),
    path('upload-profile-photo/', views.upload_profile_photo, name='upload_profile_photo'),
    path('comment_reply/', views.create_reply, name='create_reply'),


] 

merge/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import *
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('polls/', include('polls.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("polls/", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django_extensions.db.fields import AutoSlugField
from django.utils.timezone import now

class User(AbstractUser):
    email = models.EmailField(unique=True)
    image = models.ImageField(upload_to="my_images", blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=255, blank=True, null=True)
    firstname = models.CharField(max_length=255, blank=True, null=True)
    lastname = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.firstname} {self.lastname}" if self.firstname and self.lastname else ""


class Catagory(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = AutoSlugField(max_length=100, unique=True, populate_from='name')
    
    def __str__(self):
        return self.name

class Tags(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    slug = AutoSlugField(max_length=100, unique=True, populate_from='name')
    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    slug = AutoSlugField(max_length=100, unique=True, populate_from='title')
    thumbnail = models.ImageField(upload_to="my-thumbnail", blank=True, null=True)
    feature = models.ImageField(upload_to="my-feature", blank=True, null=True)
    catagory = models.ForeignKey(Catagory, on_delete=models.CASCADE, blank=True, null=True)
    tag = models.ManyToManyField(Tags, blank=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def  __str__(self):
        return self.title

class Comment(models.Model):
    sno = models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null = True, blank = True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # name = models.CharField(max_length=250)
    body = models.TextField(max_length=500)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True, blank = True)
    # email = models.EmailField(unique=True)
    timestamp = models.DateTimeField(default=now)
    
    def __str__(self):
        return f'Comment by {self.user} on {self.post}'


class Reply(models.Model):
    sno = models.AutoField(primary_key=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null = True, blank = True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE, related_name="comment_replies")
    # name = models.CharField(max_length=250)
    body = models.TextField(max_length=500)
    # parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True, blank = True)
    # email = models.EmailField(unique=True)
    timestamp = models.DateTimeField(default=now)
    
    def __str__(self):
        return f'Comment by {self.user} on {self.post} is {self.body}'

blog/forms.py
from django import forms

from .models import Post, User,Tags,Comment, Catagory,Reply

from django.contrib.auth import authenticate,login,logout


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('author', 'title', 'text','thumbnail','feature','catagory', 'tag')


class UserForm(forms.ModelForm):
    username = forms.CharField(
        label='User Name',
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'username', 'name': 'username'})
    )
    password=forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'col-10', 'id': 'password', 'name': 'password'})
    )
    class Meta:
        model = User
        fields = ("username","password")


class ProfilePhotoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['image']

        

class SignupForm(forms.ModelForm):

    
    username=forms.CharField(
        label='User Name',
        widget=forms.TextInput(attrs={'class': 'col-8', 'id': 'username', 'name': 'username'})
    )

    firstname=forms.CharField(
        label='First name',
        widget=forms.TextInput(attrs={'class': 'col-8', 'id': 'firstname', 'name': 'firstname'}),
    )
    lastname=forms.CharField(
        label='last name',
        widget=forms.TextInput(attrs={'class': 'col-8', 'id': 'lastname', 'name': 'lastname'}),
    )
    
    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'col-8', 'id': 'email', 'name': 'email'})
    )
    password=forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'col-8', 'id': 'password', 'name': 'password'})
    )
    repassword=forms.CharField(
        label="Re-Password",
        widget=forms.PasswordInput(attrs={'class': 'col-8', 'id': 'repassword', 'name': 'repassword'})
    )
    city=forms.CharField(
        label="City",
        widget=forms.TextInput(attrs={'class':'col-8','id':'city','name':'city'})
    )
    state=forms.CharField(
        label="state",
        widget=forms.TextInput(attrs={'class':'col-8','id':'state','name':'state'})
    )
    image=forms.ImageField(
        label="Image",
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file col-8', 'id': 'image', 'name': 'image'})
    )
    class Meta:
        model = User
        fields = ["username","firstname","lastname","email","password","repassword","city","state","image"]


class UserProfileForm(forms.ModelForm):
    image = forms.ImageField(
    label='',
    widget=forms.ClearableFileInput(attrs={'class': 'form-control-file ', 'id': 'image', 'name': 'image'})
    )

    class Meta:
        model = User
        fields = ('image','firstname','lastname','city','state')


class CommentForm(forms.ModelForm):
   
    body=forms.CharField(
        label='Comment',
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'body', 'name': 'body'})
    )
    # name=forms.CharField(
    #     label='Name',
    #     widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'name', 'name': 'name'})
    # )
    # email=forms.CharField(
    #     label='Email',
    #     widget=forms.EmailInput(attrs={'class': 'col-10', 'id': 'email', 'name': 'email'})
    # )
    class Meta:
        model = Comment
        fields = ['body',]


class ReplyForm(forms.ModelForm):
     body=forms.CharField(
        label='Reply',
        widget=forms.TextInput(attrs={'class': 'col-10', 'id': 'body', 'name': 'body'})
    )
     class Meta:
        model = Reply
        fields = ['body',]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post, User, Catagory, Tags, Comment,Reply
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import PostForm, UserForm, SignupForm, UserProfileForm, ProfilePhotoForm, CommentForm,ReplyForm
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by(
        "published_date"
    )
    for post in posts:
        if post.tag:
            print(post.tag.name, ">>>>>>>>>>>>>>>>>>>")
        else:
            print("No tag associated with post:", post.slug)
    return render(request, "blog/post_list.html", {"posts": posts})


def category(request,slug):
    print(request, '>>>>>>>>>>>>>>>>>>>', slug)
    categories = Post.objects.filter(catagory__slug=slug)
    return render(request, "blog/category.html", {"categories":categories})


def tag(request, slug):
    print(slug)
    if slug:
        tags = Post.objects.filter(tag__slug=slug).order_by("published_date")
    else:
        tags = Post.objects.all().order_by("published_date")
    return render(request, "blog/tag.html", {"tags": tags})


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            # post.author = request.user
            post.published_date = timezone.now()
            post.save()
            tags = form.cleaned_data['tag']
            post.tag.set(tags)  # Set the tags for the post
            return redirect("post_detail", slug=post.slug)
    else:
        form = PostForm()
    return render(request, "blog/post_edit.html", {"form": form})
            

def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            tags = form.cleaned_data['tag']
            post.tag.set(tags)
            return redirect("post_detail", slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, "blog/post_edit.html", {"form": form})


def postcomment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            post = get_object_or_404(Post, id=request.POST.get('post_id'))
            comment.post = post
            comment.user = request.user
            parent_id = request.POST.get('parent_id')
            if parent_id:
                comment.parent = get_object_or_404(Comment, id=parent_id)
            comment.save()
            return redirect('post_detail', slug=post.slug)
    return redirect('post_list')


def create_reply(request):
    comment = request.POST.get('comment_sno')
    parent_comment = get_object_or_404(Comment, sno=comment)
    # parent_commentr = Comment.objects.get(id=comment)
    post = parent_comment.post
    if request.method == 'POST':
        print(request.POST)
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.post = post
            reply.comment = parent_comment
            reply.user = request.user  
            reply.save()
            return redirect('post_detail', slug=post.slug)
    else:
        form = ReplyForm()
    return render(request, 'blog/post_detail.html', {'form': form, 'post': post,'parent_comment': parent_comment,})


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = Comment.objects.filter(post=post).select_related('user', 'parent')
    form = CommentForm()
    return render(request, 'blog/post_detail.html', {
        'post': post,
        'comments': comments,
        'form': form,
        'user': request.user,
    })


def user_login(request):
    form = UserForm()
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        print(username, "uuuuuuuuuuuuuuuuuuuuuuuuuuuuu")
        if user is not None:
            print("yes")
            login(request, user)
            return redirect("/", "Welcome, {}!".format(request.user.username))
    return render(request, "blog/userlogin.html", {"form": form})


def user_signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.password = make_password(form.cleaned_data['password'])  
            user.save()
            messages.success(request, "Your Account has been successfully created!")
            return redirect("user-login")
    else:
        form = SignupForm()
    return render(request, "blog/usersignup.html", {"form": form})
    

def user_signout(request):
    logout(request)
    return redirect("user-login")


@login_required
def edit_profile(request, user_id):
    user_profile = get_object_or_404(User, id=user_id)
    if request.method == "POST":
        user_profile_form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if user_profile_form.is_valid():
            user_profile_form.save()
            messages.success(request, "Your profile has been successfully updated!")
            return redirect("post_list") 
    else:
        user_profile_form = UserProfileForm(instance=user_profile)
    return render(request, "blog/user_edit.html", {"user_profile_form": user_profile_form})


@login_required
def user_detail(request, user_id):
    user = get_object_or_404(User, id=user_id)
    return render(request, "blog/user_detail.html", {"user": user})


def upload_profile_photo(request):
    if request.method == "POST":
        form = ProfilePhotoForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("post_list")
    else:
        form = ProfilePhotoForm(instance=request.user)
    return render(request, "blog/user_edit.html", {"form": form})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Girls Blog</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <style>
        body {
            font-family: 'Lobster', sans-serif;
            background-color: #f8f9fa;
        }
        header.page-header {
            background-color: #343a40;
            padding: 20px 0;
            margin-bottom: 20px;
        }
        header.page-header h1 a {
            color: #ffffff;
            text-decoration: none;
        }
        header.page-header h1 a:hover {
            color: #adb5bd;
        }
        .top-menu {
            margin-left: 10px;
        }
        main.content {
            padding: 20px;
            background: #ffffff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .dropdown-toggle::after {
            margin-left: 0.255em;
        }
    </style>
</head>

<body>
    <header class="page-header">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <h1><a href="{% url 'post_list' %}">My Blogs</a></h1>
                <h1><a href="{% url 'polls:index' %}">Polls</a></h1>
                {% if request.user.is_authenticated %}
                
                <div class="d-flex align-items-center">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <a href="{% url 'user_detail' user_id=request.user.id %}">{{ request.user.username|title }}</a>
                        </li>
                        
                        <li class="list-inline-item">
                            <a href="{% url 'user-signout' %}">Logout</a>
                        </li>
                    </ul>
                    <a href="{% url 'post-new' %}" class="btn btn-primary top-menu">
                        {% include './icons/file-earmark-plus.svg' %}
                    </a>
                </div>
                {% else %}
                <div class="dropdown">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                        Log In
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'user-login' %}">Log In</a></li>
                        <li><a class="dropdown-item" href="{% url 'user-signup' %}">Sign Up</a></li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </header>
    <main class="content container">
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

blog/templates/blog/category.html
{% extends 'blog/base.html' %}
{% block content %}
<div style="display:flex; gap:20px; flex-wrap: wrap;">
    {% for post in categories %}
    <div class="card" style="width: 20rem;">
        <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}{% endif %}" alt="Card image cap" width=200px height=200px>
        <div class="card-body">
            <h4 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h4>
            <div style="display:flex; gap:30px">
                <p><b>Category:-&nbsp;<a href="{% url 'category' slug=post.catagory.slug %}">{{ post.catagory }}</a></b></p>
            </div>
            <p class="card-text">{{ post.text|truncatewords:30 }}<br>
                <b>Published At:-&nbsp;</b>{{ post.published_date|date:"Y-m-d" }}<br>
                
                
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/edit_profile.html
{% extends 'blog/base.html' %}
{% block content %}

{% if request.user.profile_picture %}
        <img src="{{ request.user.edit_profile.url }}" alt="Profile Picture">
    {% else %}
        <p>No profile picture uploaded.</p>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload Profile Picture</button>
    </form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<article class="post">
    <div style="display: flex; align-items: center; padding: 10px; margin-bottom: 15px;">
        <img class="card-img-top" src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% endif %}" alt="Thumbnail"
            style="border-radius: 50%; height: 60px; width: 60px; border-style: solid ; border-width: 2px; margin-right: 10px;">
        <h2 style="margin: 0;">{{ post.title }}</h2>
        <!-- Margin added to prevent title from sticking to the thumbnail -->
    </div>
    <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}{% endif %}"" alt=" Card image cap"
        style="height: 500px; width: 100%; border-radius: 20px; border-style: ridge; border-width: 10px;"><br>
    <aside class="actions">
        <a class="btn btn-secondary" href="{% url 'post_edit' slug=post.slug %}" style="margin: 10px;">
            {% include './icons/pencil-fill.svg' %}
        </a>
    </aside>
    <p style="margin-top: 15px;"><b>Catagory:-&nbsp;</b><a href="{% url 'category' slug=post.catagory.slug %}">{% if post.catagory %}{{ post.catagory }}{% endif %}</a></p>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.published_date %}
    <!-- <time class="date"> -->
    <strong>Published At:-&nbsp;</strong>{{ post.published_date|date:"Y-m-d" }}<br>
    <!-- </time> -->
    <strong>Published By:-&nbsp;</strong>{% if post.author %}{{ post.author|title }}{% endif %}
    {% endif %}
    <br>
    <b>Tags:-</b>
    {% for tag in post.tag.all %}
    <a href="{% url 'tag' slug=tag.slug %}"><small>{{tag.name}} <b>||</b></small></a>
    {% endfor %}
    <br>
</article>

<div class="container">
    <h4>Add a Comment</h4>

    <form action="{% url 'postcomment' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="post_id" value="{{ post.id }}">
        <button type="submit">Post Comment</button>
    </form>

    {% for comment in comments %}
    <div class="row my-3">
        <div class="row-md-1 w-100">
            {% if comment.user.image %}
            <img src="{{ comment.user.image.url }}" alt="Profile Photo"
                class="rounded-circle mb-4 justify-content-center" width="60px" height="60px">
            {% else %}
            <img src="https://via.placeholder.com/100" alt="Profile Photo" class="rounded-circle mb-3">
            {% endif %}
        </div>
        <div class="col-md-11">
            <strong>{{ comment.user.username|title }}</strong> at {{ comment.timestamp }}
            <div>{{ comment.body }}</div>

            <div class="reply mx-0">
                <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse"
                    data-bs-target="#replyBox{{comment.sno}}" aria-expanded="false"
                    aria-controls="replyBox{{comment.sno}}">
                    Reply
                </button>
                <div class="collapse" id="replyBox{{comment.sno}}">
                    <div class="card card-body my-2">
                        <form action="{% url 'create_reply' %}" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="hidden" name="comment_sno" value="{{ comment.sno }}">
                            <button type="submit">Post Reply</button>
                        </form>

                        {% for rp in comment.comment_replies.all %}
                        <div class="row my-3">
                            <div class="col-md-1 w-100">
                                {% if rp.user.image %}
                                <img src="{{ rp.user.image.url }}" alt="Profile Photo"
                                    class="rounded-circle mb-4 justify-content-center" width="60px" height="60px">
                                {% else %}
                                <img src="https://via.placeholder.com/100" alt="Profile Photo"
                                    class="rounded-circle mb-3">
                                {% endif %}
                            </div>
                            <div class="col-md-11">
                                <strong>{{ rp.user.username|title }}</strong> at {{ rp.timestamp }}
                                <div>{{ rp.body }}</div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% else %}
<article class="post">
    <div style="display: flex; align-items: center; padding: 10px; margin-bottom: 15px;">
        <img class="card-img-top" src="{% if post.thumbnail %}{{ post.thumbnail.url }}{% endif %}" alt="Thumbnail"
            style="border-radius: 50%; height: 60px; width: 60px; border-style: solid ; border-width: 2px; margin-right: 10px;">
        <h2 style="margin: 0;">{{ post.title }}</h2>
        <!-- Margin added to prevent title from sticking to the thumbnail -->
    </div>
    <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}{% endif %}"" alt=" Card image cap"
        style="height: 500px; width: 100%; border-radius: 20px; border-style: ridge; border-width: 10px;"><br>

    <p style="margin-top: 15px;"><b>Catagory:-&nbsp;</b>
        <a href="{% url 'category' slug=post.catagory.slug %}">{% if post.catagory %}{{ post.catagory }}{% endif %}</a>
    </p>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.published_date %}
    <!-- <time class="date"> -->
    <strong>Published At:-&nbsp;</strong>{{ post.published_date|date:"Y-m-d" }}<br>
    <!-- </time> -->
    <strong>Published By:-&nbsp;</strong>{% if post.author %}{{ post.author|title }}{% endif %}
    {% endif %}
    <br>
    <b>Tags:-</b>
    {% for tag in post.tag.all %}
    <a href="{% url 'tag' slug=tag.slug %}"><small>{{tag.name}} <b>||</b></small></a>
    {% endfor %}
</article>
{% endif %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<div>
    <h2>New post</h2>
    <form method="post" enctype="multipart/form-data" class="post-form">{% csrf_token %}
        {{ form.as_p }}
    </form>
    <div style="display: flex; justify-content: right;">
        <button type="submit" class="btn btn-secondary">Save</button>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="row">
    {% for post in posts %}
    <div class="col-12 col-md-12 col-lg-4 mb-4">
        <div class="card" style="width: 100%;">
            <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}{% endif %}" alt="Card image cap"
                style="width: 100%; height: 260px;">
            <div class="card-body">
                <h4 class="card-title">
                    <a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a>
                </h4>
                <div style="display:flex; gap:30px">
                    <p><b>Category:-&nbsp;<a href="{% url 'category' slug=post.catagory.slug %}">{{ post.catagory}}</a></b></p>
                </div>
                <p class="card-text">{{ post.text|truncatewords:30 }}<br>
                    <b>Published At:-&nbsp;</b>{{ post.published_date|date:"Y-m-d" }}<br>
                    <strong>Published By:-&nbsp;</strong>{% if post.author %}{{ post.author|title }}{% endif %}
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- </div> -->
{% endblock %}

blog/templates/blog/tag.html
{% extends 'blog/base.html' %}
{% block content %}
<div style="display:flex; gap:20px; flex-wrap: wrap;">
    {% for post in tags %}
    <div class="card" style="width: 20rem;">
        <img class="card-img-top" src="{% if post.feature %}{{ post.feature.url }}{% endif %}" alt="Card image cap" width=200px height=200px>
        <div class="card-body">
            <h4 class="card-title"><a href="{% url 'post_detail' slug=post.slug %}">{{ post.title }}</a></h4>
            <div style="display:flex; gap:30px">
                <p><b>Category:-&nbsp;<a href="{% url 'category' slug=post.catagory.slug %}">{{ post.catagory }}</a></b></p>
            </div>
            <p class="card-text">{{ post.text|truncatewords:30 }}<br>
                <b>Published At:-&nbsp;</b>{{ post.published_date|date:"Y-m-d" }}<br>
                <b>Tags:-</b>
                {% for tag in post.tag.all %}
                <a href="{% url 'tag' slug=tag.slug %}"><small>{{ tag.name }} <b>||</b></small></a>
                {% endfor %}
            </p>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/upload_profile_photo.html
{% extends 'blog/base.html' %}
{% block content %}


<h2>Upload Profile Photo</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>

    {% if user.profile_photo %}
        <img src="{{ user.profile_photo.url }}" alt="Profile Photo">
    {% endif %}

    <!-- <a href="{% url 'upload_profile_photo' %}">Upload Profile Photo</a> -->

{% endblock %}
    